"""
Page 3 – User Profile & History
---------------------------------
Shows: progress graphs, pie chart of error types,
session history table, per-session report, overall downloadable PDF report.
"""

from __future__ import annotations

import io
import json
import smtplib
import sys
from datetime import datetime
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from dotenv import load_dotenv
load_dotenv(PROJECT_ROOT / ".env")

import streamlit as st
import pandas as pd

from app.ui import configure_page

configure_page(
    title="My Profile",
    icon="👤",
    layout="wide",
)

from infrastructure import database






def _build_session_report(session: dict, detail: list) -> bytes:
    lines = [
        "=" * 60,
        "  PRONUNCIATION SESSION REPORT",
        "=" * 60,
        f"Session ID   : #{session['id']}",
        f"Date         : {session['started_at'][:10]}",
        f"Sentence     : {session['sentence']}",
        f"Overall Score: {session['overall_score']}/100",
        "",
        "WORD-BY-WORD ANALYSIS",
        "-" * 40,
    ]
    for wr in detail:
        acc  = round(wr["best_accuracy"] * 100)
        status = "PASSED" if wr["passed"] else "NEEDS WORK"
        lines.append(f"\n  Word: {wr['word'].upper()}  [{status}]  Score: {acc}/100")
        for e in wr.get("errors", []):
            lines.append(
                f"    Error: {e.get('error_type','').upper()}"
                f"  Expected: /{e.get('expected_phoneme','?')}/"
                f"  Got: /{e.get('detected_phoneme','?')}/"
                f"  Severity: {e.get('severity','').capitalize()}"
            )
    if session.get("summary"):
        lines += ["", "COACH FEEDBACK", "-" * 40, session["summary"]]
    lines += ["", "=" * 60]
    return "\n".join(lines).encode()


def _build_overall_report(name: str, email: str, stats: dict, sessions: list) -> bytes:
    lines = [
        "=" * 60,
        "  OVERALL PRONUNCIATION PROGRESS REPORT",
        "=" * 60,
        f"Student       : {name}",
        f"Email         : {email}",
        f"Report Date   : {datetime.utcnow().strftime('%Y-%m-%d')}",
        "",
        "SUMMARY STATISTICS",
        "-" * 40,
        f"Total Sessions    : {stats['total_sessions']}",
        f"Average Score     : {stats['avg_score']}/100",
        f"Best Score        : {stats['best_score']}/100",
        f"Total Words       : {stats['total_words']}",
        f"Words Passed      : {stats['passed_words']}",
        "",
        "ERROR BREAKDOWN",
        "-" * 40,
    ]
    for etype, cnt in stats.get("error_types", {}).items():
        lines.append(f"  {etype.capitalize():15s}: {cnt} occurrences")
    lines += [
        "",
        "SESSION HISTORY (newest first)",
        "-" * 40,
    ]
    for s in sessions[:20]:
        lines.append(
            f"  {s['started_at'][:10]}  Score: {s['overall_score']:3d}/100  "
            f"Sentence: {s['sentence'][:50]}"
        )
    lines += [
        "",
        "=" * 60,
        "Generated by AI-Based Pronunciation Error Detection System",
        "=" * 60,
    ]
    return "\n".join(lines).encode()


def _send_report_email(to_email: str, name: str, report_bytes: bytes) -> bool:
    import logging
    import os

    smtp_host = os.getenv("SMTP_HOST", "")
    smtp_port = int(os.getenv("SMTP_PORT", "587"))
    smtp_user = os.getenv("SMTP_USER", "")
    smtp_pass = os.getenv("SMTP_PASS", "")

    if not smtp_host or not smtp_user:
        return False

    try:
        msg = MIMEMultipart()
        msg["From"]    = smtp_user
        msg["To"]      = to_email
        msg["Subject"] = f"Your Pronunciation Progress Report - {name}"
        msg.attach(MIMEText(f"Hi {name},\n\nPlease find your pronunciation progress report attached.\n\nKeep practising!\n", "plain"))
        att = MIMEApplication(report_bytes, _subtype="txt")
        att.add_header("Content-Disposition", "attachment", filename="pronunciation_report.txt")
        msg.attach(att)

        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.starttls()
            server.login(smtp_user, smtp_pass)
            server.sendmail(smtp_user, to_email, msg.as_string())
        return True
    except Exception as exc:
        logging.getLogger(__name__).warning("Email send failed: %s", exc)
        return False

# ── Auth guard ────────────────────────────────────────────────────────────────
if not st.session_state.get("user_id"):
    st.warning("Please login first.")
    if st.button("← Go to Login"):
        st.switch_page("pages/0_Login.py")
    st.stop()

user_id   = st.session_state["user_id"]
user_name = st.session_state.get("user_name", "User")
email     = st.session_state.get("user_email", "")

database.init_db()
stats    = database.get_user_stats(user_id)
sessions = database.get_user_sessions(user_id, limit=100)

# ── CSS ───────────────────────────────────────────────────────────────────────
st.markdown("""
<style>
.stat-card { background:#f8f9fa; border-radius:14px; padding:18px 16px; text-align:center; border:1px solid #e9ecef; }
.stat-num  { font-size:2.2rem; font-weight:800; line-height:1.1; }
.stat-lbl  { font-size:0.78rem; color:#888; margin-top:4px; }
.badge     { display:inline-block; padding:3px 10px; border-radius:20px; font-size:0.78rem; font-weight:700; }
.badge-green { background:#d5f5e3; color:#1a7a45; }
.badge-red   { background:#fde8e8; color:#c0392b; }
</style>
""", unsafe_allow_html=True)

# ── Header ────────────────────────────────────────────────────────────────────
col_h, col_btn = st.columns([4, 1])
with col_h:
    st.title(f"👤 {user_name}'s Profile")
    st.caption(f"📧 {email}  ·  Member since {sessions[-1]['started_at'][:10] if sessions else 'N/A'}")
with col_btn:
    if st.button("🚪 Logout", use_container_width=True):
        for k in ["user_id","user_name","username","user_email","stage","report","analyzer"]:
            st.session_state.pop(k, None)
        st.switch_page("pages/0_Login.py")

st.divider()

# ── Stats row ─────────────────────────────────────────────────────────────────
c1, c2, c3, c4, c5 = st.columns(5)
def _card(col, num, label, color="#5B9BD5"):
    col.markdown(
        f'<div class="stat-card">'
        f'<div class="stat-num" style="color:{color}">{num}</div>'
        f'<div class="stat-lbl">{label}</div></div>',
        unsafe_allow_html=True
    )

_card(c1, stats["total_sessions"],   "Sessions",       "#5B9BD5")
_card(c2, f"{stats['avg_score']}",   "Avg Score",      "#27ae60")
_card(c3, stats["best_score"],        "Best Score",     "#f39c12")
_card(c4, stats["total_words"],       "Words Practised","#9B7BC8")
_card(c5, stats["passed_words"],      "Words Passed",   "#e74c3c")

st.markdown("")

# ── Charts row ────────────────────────────────────────────────────────────────
if sessions:
    df_scores = pd.DataFrame([
        {"Session": i+1, "Score": s["overall_score"], "Date": s["started_at"][:10]}
        for i, s in enumerate(reversed(sessions))
    ])

    ch1, ch2 = st.columns([3, 2])

    with ch1:
        st.subheader("📈 Score Trend")
        st.line_chart(df_scores.set_index("Session")["Score"], color="#5B9BD5", height=220)

    with ch2:
        st.subheader("🥧 Error Types")
        err = stats.get("error_types", {})
        if err:
            df_err = pd.DataFrame({
                "Type": [k.capitalize() for k in err.keys()],
                "Count": list(err.values()),
            })
            st.bar_chart(df_err.set_index("Type"), color="#9B7BC8", height=220)
        else:
            st.info("No errors recorded yet.")

    st.divider()

# ── Session history table ─────────────────────────────────────────────────────
st.subheader("📋 Practice History")

if not sessions:
    st.info("No practice sessions yet. Record a sentence to get started!")
else:
    # Build table
    rows = []
    for s in sessions:
        score = s["overall_score"]
        badge = "🟢" if score >= 75 else ("🟡" if score >= 50 else "🔴")
        rows.append({
            "#":        s["id"],
            "Date":     s["started_at"][:10],
            "Sentence": s["sentence"][:60] + ("…" if len(s["sentence"]) > 60 else ""),
            "Score":    f"{badge} {score}/100",
        })
    df_hist = pd.DataFrame(rows)
    st.dataframe(df_hist, use_container_width=True, hide_index=True)

    st.divider()

    # ── Per-session report viewer ───────────────────────────────────────────
    st.subheader("🔍 View Session Report")
    session_options = {f"Session #{s['id']} — {s['started_at'][:10]} — {s['sentence'][:40]}": s["id"]
                       for s in sessions}
    chosen_label = st.selectbox("Choose a session", list(session_options.keys()))
    chosen_id    = session_options[chosen_label]
    chosen_sess  = next(s for s in sessions if s["id"] == chosen_id)

    detail = database.get_session_detail(chosen_id)

    col_info, col_dl = st.columns([3, 1])
    with col_info:
        score = chosen_sess["overall_score"]
        color = "#27ae60" if score >= 75 else ("#f39c12" if score >= 50 else "#e74c3c")
        st.markdown(
            f'**Score:** <span style="color:{color};font-weight:800;font-size:1.3rem">{score}/100</span>',
            unsafe_allow_html=True,
        )
        st.caption(chosen_sess.get("summary", "") or "")

    with col_dl:
        report_bytes = _build_session_report(chosen_sess, detail)
        st.download_button(
            "⬇️ Download PDF",
            data=report_bytes,
            file_name=f"session_{chosen_id}_report.txt",
            mime="text/plain",
            use_container_width=True,
        )

    # Word table
    if detail:
        for wr in detail:
            icon = "✅" if wr["passed"] else "❌"
            acc  = round(wr["best_accuracy"] * 100)
            with st.expander(f"{icon} **{wr['word'].upper()}** — {acc}/100"):
                errs = wr.get("errors", [])
                if errs:
                    st.table([{
                        "Expected": e.get("expected_phoneme","—"),
                        "Detected": e.get("detected_phoneme","—"),
                        "Type":     e.get("error_type","").capitalize(),
                        "Severity": e.get("severity","").capitalize(),
                    } for e in errs])
                else:
                    st.success("No errors detected for this word.")

    st.divider()

    # ── Overall report download + email ────────────────────────────────────
    st.subheader("📊 Overall Report")
    overall_bytes = _build_overall_report(user_name, email, stats, sessions)

    dl_col, mail_col = st.columns(2)
    with dl_col:
        st.download_button(
            "⬇️ Download Overall Report",
            data=overall_bytes,
            file_name="overall_pronunciation_report.txt",
            mime="text/plain",
            use_container_width=True,
            type="primary",
        )
    with mail_col:
        send_email = st.text_input("Send to email:", value=email, key="email_send")
        if st.button("📧 Send Report to Email", use_container_width=True):
            if "@" not in send_email:
                st.error("Please enter a valid email.")
            else:
                sent = _send_report_email(send_email, user_name, overall_bytes)
                if sent:
                    st.success(f"✅ Report sent to {send_email}")
                else:
                    st.warning("⚠️ Email sending requires SMTP configuration in .env. Report downloaded instead.")
                    st.download_button(
                        "⬇️ Download instead",
                        data=overall_bytes,
                        file_name="overall_pronunciation_report.txt",
                        mime="text/plain",
                    )


# ── Navigation ────────────────────────────────────────────────────────────────
st.divider()
if st.button("🎤 Back to Pronunciation Checker", type="primary"):
    st.switch_page("streamlit_app.py")


# ── Report builders ───────────────────────────────────────────────────────────





